package ru.vitrina.sdk.installation

import kotlin.random.Random

/**
 * Persistent storage used for the installation identifier generated by VitrinaKit.
 *
 * The identifier stabilizes paywall assignment and analytics for one app installation. It is not
 * an account and does not own purchases: reinstalling the app may lose it, while store restore
 * remains the source of purchase recovery.
 */
interface VitrinaKitInstallationIdStorage {
    /** Returns the stored installation identifier, or `null` before the first SDK activation. */
    fun read(): String?

    /** Persists the current installation identifier. */
    fun write(installationId: String)
}

internal expect fun defaultInstallationIdStorage(): VitrinaKitInstallationIdStorage

internal fun loadOrCreateInstallationId(storage: VitrinaKitInstallationIdStorage): Result<String> = runCatching {
    storage.read()?.trim()?.takeIf { installationId -> installationId.isNotEmpty() }
        ?: newInstallationId().also(storage::write)
}

internal fun rotateInstallationId(storage: VitrinaKitInstallationIdStorage): Result<String> = runCatching {
    newInstallationId().also(storage::write)
}

private fun newInstallationId(): String {
    val bytes = Random.nextBytes(UuidByteCount)
    bytes[UuidVersionIndex] = ((bytes[UuidVersionIndex].toInt() and UuidVersionMask) or UuidVersionBits).toByte()
    bytes[UuidVariantIndex] = ((bytes[UuidVariantIndex].toInt() and UuidVariantMask) or UuidVariantBits).toByte()
    return buildString(UuidStringLength) {
        bytes.forEachIndexed { index, byte ->
            if (index in UuidHyphenIndexes) {
                append('-')
            }
            append(HexDigits[(byte.toInt() ushr NibbleBitCount) and NibbleMask])
            append(HexDigits[byte.toInt() and NibbleMask])
        }
    }
}

private const val UuidByteCount = 16
private const val UuidStringLength = 36
private const val UuidVersionIndex = 6
private const val UuidVariantIndex = 8
private const val UuidVersionMask = 0x0F
private const val UuidVersionBits = 0x40
private const val UuidVariantMask = 0x3F
private const val UuidVariantBits = 0x80
private const val NibbleBitCount = 4
private const val NibbleMask = 0x0F
private val UuidHyphenIndexes = setOf(4, 6, 8, 10)
private const val HexDigits = "0123456789abcdef"
